### ISSUE TITLE
USER STORY: Create bookings form

### ISSUE THREAD

**Issue by JavierBL89** [JavierBL89/OP-Restaurant-Code-Inst-Project#13]
# User story

In order to book a table, i can select date, time and size party to my choise

## Acceptance criteria:

- Form must provide a calendar
- Form only show available slot times
- Must have  an input number for size party
- Size party will have a limit of 12px
- Form must get customer personal details:
    1.Name
    2.Surname
    3.Contact number
       - Prefix options
- Submit button wiil submit all the fields together
- Will chech if coustomer has previuos records

### Tasks

- [ ] Design forms layout
- [ ] Design submit button
- [ ] Create HTML and CSS code
