### ISSUE TITLE
USER STORY 2: Call to action section

### ISSUE THREAD

**Issue by JavierBL89** [JavierBL89/OP-Restaurant-Code-Inst-Project#2]
# User Story 

In order to make bookings, as a **user**, i want an easy to find bookings section

## Acceptance criteria:

- Must be on the homepage
- Must be straight to users eyes
- Will have a background image

### Tasks

- [x] Choose a background image
- [x] Store image in Cloudinary
- [x] Create HTML adn CSS code
