### ISSUE TITLE
User story: Provide feedback to users after submiting booking request

### ISSUE THREAD

**Issue by JavierBL89** [JavierBL89/OP-Restaurant-Code-Inst-Project#24]
# User Story 

In order to make sure i have booked successfully , as a **user**, i want to receive feedback after submiting the booking request

## Acceptance criteria:

- Show message if booking request is successful
- Show message if booking request date is  booked out
- Show message if there are other bookings for same date or same week
- 
### Tasks

- [x] Create new view
- [x] Create new template 
- [x] Get and populate existing bookings data
- [x] Design layout message
- [x] Create CSS code
