### ISSUE TITLE
USER STORY: Cancel bookings

### ISSUE THREAD

**Issue by JavierBL89** [JavierBL89/OP-Restaurant-Code-Inst-Project#25]
# User Story 

In order to **cancel my booking", as a **user**, i want to have the option of cancel my bookings through the website 

## Acceptance criteria:

- User must enter the email address and phone number to check if existing reservations
- Must have a secure second question to be sure they want to continue with the cancelation proccess

### Tasks

- [ ] Design cancelation section layout
- [ ] Create view
- [ ] Create template
- [ ] Design buttons
- [ ] Design security modal
- [ ] Create JavaScript code
- [ ] Create CSS code
