### ISSUE TITLE
USER STORY 4: Workteam section

### ISSUE THREAD

**Issue by JavierBL89** [JavierBL89/OP-Restaurant-Code-Inst-Project#4]
# User Story 

In order to make the user familiar to the workteam and company, as a **owner**, i provide a section with the workteam

## Acceptance criteria:

- Will have the Head Cheff and a floor team photo
- Will have a brief introductory text each

### Tasks

- [x] Design the section layout
- [x] Create the HTML and CSS code
- [x] Choose the pictures
- [x] Include a brief text
- [x] Fully Responsive
