### ISSUE TITLE
USER STORY 5: Footer section

### ISSUE THREAD

**Issue by JavierBL89** [JavierBL89/OP-Restaurant-Code-Inst-Project#5]
# User Story 

In order to provide a nice site design, contact details, social media links and improve navigation, as a **owner**, i want to have a nice footer section

## Acceptance criteria:

- Will have contact details
- Will have 3 social media links
    1.Facebook
    2.Insta
    3.Twiter
- Will have companys name
- Will have Copy Right

### Tasks

- [x] Design footer layout
- [x] Design social icons
- [x] Link social icons to social sites
- [x] Fully responsive
- [x] Create HTML and CSS code
- [x] Create JS code for automatic year
- [x] Fully responsive
