### ISSUE TITLE
USER STORY: Typography

### ISSUE THREAD

**Issue by JavierBL89** [JavierBL89/OP-Restaurant-Code-Inst-Project#7]
# User story

As a **coder** , I can **choose a nice typography** so that **improve user experience and give a unique design to the site**

## Acceptance criteria:

- Will have 2 different fonts
- Main site's font will be Serif

### Tasks

- [x] Choose Serif font
- [x] Choose logo text font
- [x] Choose font size for every element
- [x] Make font size fully responsive
