### ISSUE TITLE
USER STORY: Animations

### ISSUE THREAD

**Issue by JavierBL89** [JavierBL89/OP-Restaurant-Code-Inst-Project#8]
# User story

As a **coder** , I can **provide nice animations to elements** so that **improve users experince and gice a unique design to the site**

## Acceptance criteria:

- Prium.github framework and Bootstrap frameworks for animations
- Nice and subtle animations to users eyes
- Hover animations
- Scroll down animations
- Drop downs animations
- 

### Tasks

- [x] Choose and design hover animations
- [x] Choose scroll down animations
- [x] Choose collapse animations
- [x] Create CSS code
