### ISSUE TITLE
USER STORY: Gallery

### ISSUE THREAD

**Issue by JavierBL89** [JavierBL89/OP-Restaurant-Code-Inst-Project#9]
# User story

As a **coder** , I can **provide a gallery section** so that **users can see what the restaurant is about in order to appeal coustomers make a booking a visit the venue**

## Acceptance criteria:

- Gallery will be made up of nice dishes pictures
- Gallery will be displayed on the homepage

### Tasks

- [x] Design gallery layout
- [x] Choose pictures to be shown
- [x] Create HTML and CSS code
